config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  namespace :api do
    resources :reports
    resources :expenses
    resources :sessions
    resources :accounts
    post '/sessions/logout', to: 'sessions#logout'
  end

  get '*path', to: 'home#index'

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :amount
  validates_presence_of :description

  #used for Api::Reporting to group sets of expenses
  def week
    self.date ? self.date.strftime('%Y-%W') : ('0000-00')
  end
end

app/models/report_generator.rb
class ReportGenerator
  def self.by_week(user)

    user.expenses.group_by(&:week).inject({}) do |result, week|
      amount  = week.second.inject(0){ |r,expense| r + expense.amount }
      total_expenses = week.second.count
      average = amount/total_expenses
      result[week.first] = {"amount" => amount, "average" => average, "total_expenses" => total_expenses}
      result
    end

  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  has_many :tokens
  has_secure_password

  def set_token
    begin
      key = SecureRandom.hex
    end while Token.find_by_key(key)
    self.tokens.create(:key => key, :expiration => 4.hours.from_now)
    key
  end

end

app/controllers/api/accounts_controller.rb
class Api::AccountsController < ActionController::Base

  def create
    if User.find_by_email(params[:email])
      render json: {success: false, message: "Duplicate Username!"}
    else
      if params[:password].blank?
        render json: {success: false, message: "Please enter a password"}
      else
        user = User.create(email: params[:email], password: params[:password])
        render json: {success: true, message: "Account Created, Logging In!", token: user.set_token}
      end
    end
  end
end

app/controllers/api/expenses_controller.rb
class Api::ExpensesController < ApplicationController
  respond_to :json

  def index
    user = current_user
    if user
      render json: user.expenses.all
    else
      render json: { message: "Unauthorized"}, status: 403
    end
  end

  def show
    if authorized?
      render json: expense
    else
      render json: { message: "Unauthorized"}, status: 403
    end
  end

  def create
    user = current_user
    if user
      render json: current_user.expenses.create(expense_params)
    else
      render json: { message: "Unauthorized"}, status: 403
    end
  end

  def update
    if authorized?
      render json: expense.update(expense_params)
    else
      render json: { message: "Unauthorized"}, status: 403
    end
  end

  def destroy
    if authorized?
      respond_with expense.destroy
    else
      render json: { message: "Unauthorized"}, status: 403
    end
  end

  private

  def expense
    Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit(:comment, :amount, :date, :description, :time)
  end

  def authorized?
    current_user.try(:id) == expense.user_id
  end

end

app/controllers/api/reports_controller.rb
class Api::ReportsController < ApplicationController
  respond_to :json

  def index
    user = current_user
    if user
      render json: ReportGenerator.by_week(user)
    else
      render json: { message: "Unauthorized"}, status: 403
    end
  end

end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < ActionController::Base

  def create
    user = User.find_by_email(params[:email])
    if user
      if user.authenticate(params["password"])
        render json: {success: true, message: "Successfully Logged In!", token: user.set_token}
      else
        render json: {success: false, message: "Please Check Password"}
      end
    else
      render json: {success: false, message: "Username Not Found"}
    end
  end

  def logout
    token = Token.all.find{|t| t.key == params[:key]}
    if token.destroy
      render json: {success: true}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user(key=request.headers.env["HTTP_API_KEY"])
    current_token(key).try(:user)
  end

  #TODO this should not be necessary, can't find token by key in ruby 1.9.3
  def current_token(key)
    Token.where("expiration >= ?", Time.now).find{|t| t.key == key}
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/expenses/_form.html.erb
<%= form_for(@expense) do |f| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% @expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<h1>Listing expenses</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.date %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.comment %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New expense</h1>

<%= render 'form' %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Date:</strong>
  <%= @expense.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @expense.comment %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/home/index.html.erb
<script type="text/x-handlebars" data-template-name="login">
    {{#if loggedIn}}
      <p>You are already logged in!</p>
    {{else}}
      <form class="form-inline" {{action login on="submit"}}>
        <h2>Log In</h2>
        {{input value=email type="text" placeholder="Email"}}
        {{input value=password type="password" placeholder="Password"}}
        {{input class="btn" type="submit" value="Log In"}}
      </form>
      {{#if errorMessage}}
        <div class="alert alert-error">{{errorMessage}}</div>
      {{/if}}
    {{/if}}
</script>

<script type="text/x-handlebars" data-template-name="signup">
      <form class="form-inline" {{action signup on="submit"}}>
        <h2>Sign Up</h2>
        {{input value=email type="text" placeholder="Email"}}
        {{input value=password type="password" placeholder="Password"}}
        {{input class="btn" type="submit" value="Sign Up!"}}
      </form>
      {{#if errorMessage}}
        <div class="alert alert-error">{{errorMessage}}</div>
      {{/if}}
</script>

<script type="text/x-handlebars" data-template-name="report" id="report">




      <table class="gridtable">
        <thead>
          <tr>
            <th>Week</th>
            <th>Total Spent</th>
            <th>Average per Transaction</th>
            <th>Number of Expenses</th>
          </tr>
        </thead>
        <tbody>
          {{#each expensesByWeek}}
            <tr>
              <td>{{this.key}}</td>
              <td>{{this.amount}}</td>
              <td>{{this.average}}</td>
              <td>{{this.total_expenses}}</td>
            </tr>
          {{/each}}
        </tbody>
      </table>
      *Expenses without a date are '0000-00'

      {{#if errorMessage}}
        <div class="alert alert-error">{{errorMessage}}</div>
      {{/if}}

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expenses</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
  <div id="ember-app"></div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>